repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: requirements-txt-fixer
- repo: https://github.com/ambv/black
  rev: 22.10.0
  hooks:
  - id: black
    args: [--line-length=80, --safe]
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
- repo: https://github.com/brianjbuck/noeval
  rev: v1.0.0
  hooks:
  - id: noeval
